apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base http-echo template
resources:
  - ../../base/http-echo

namespace: echo-test

# Rename all resources from http-echo to foo
namePrefix: ""
nameSuffix: ""

# Override labels to identify this as "foo"
commonLabels:
  app.kubernetes.io/name: foo
  app.kubernetes.io/instance: foo

# Patch to change the -text argument and metadata name
patches:
  - target:
      kind: Deployment
      name: http-echo
    patch: |-
      - op: replace
        path: /metadata/name
        value: foo
      - op: replace
        path: /spec/selector/matchLabels/app.kubernetes.io~1name
        value: foo
      - op: replace
        path: /spec/template/spec/containers/0/args/0
        value: "-text=foo"
  - target:
      kind: Service
      name: http-echo
    patch: |-
      - op: replace
        path: /metadata/name
        value: foo
      - op: replace
        path: /spec/selector/app.kubernetes.io~1name
        value: foo
